spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-been-definition-overriding: true
info:
  component: Product Service


server:
  port:9788

---
spring:
  config:
    active:
      on-profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default-schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 123321